apiVersion: v1
kind: Secret
metadata:
  name: keycloak-client-secrets
  namespace: keycloak
type: Opaque
data:
  KEYCLOAK_IMPORT_CLIENT_SECRET_BIDAN: UG40RlZmNkd4U2FBOEVLM3JYbURrdlpXSksydVp3amhOVHA1Qkw5UUhhY2JN
  KEYCLOAK_IMPORT_CLIENT_SECRET_CADRE: Z2J6MmZjeUxabkNGUXh1ZTk4QVM3ZHM1dG1XcGpNVDRyYWhrTndQVnZHSjZINFlCRHE=
  KEYCLOAK_IMPORT_CLIENT_SECRET_FHIR_SERVER_AUTH: Y3V0VzNFZG1RVkM2RHdBVVNlWGtmekw5ZzdKMlpOOGhqUnBiYW54NEhZc3lQdnI1R1Q=
  KEYCLOAK_IMPORT_CLIENT_SECRET_FHIR_WEB: Y0pqS1FMZEhydld6OTVHdGVCeGtOUzdtMlo4Uk1YdWI0bnBnQWFEVWZQeVlUNnNFcQ==
  KEYCLOAK_IMPORT_CLIENT_SECRET_OPENFN: Q0I0Rmh3cERLVWpndnJBdGJlWjg1Y0V4VHpNZFJuUTYyWE5XSHlhTFM3OUprM3N1Zkc=
  KEYCLOAK_IMPORT_CLIENT_SECRET_OPENSRP_V2: R1Q1dHJ3V0FIUjRjOGpFc0tTTmdxZmVGZG54bTJITHZwcTZWeU11YjNrVTlhSlBaeg==
  KEYCLOAK_IMPORT_CLIENT_SECRET_VACCINATOR: bk45bUp1NnNGY2tiaHZWZzdyUjNQaEthMjR5Q3JNU2ZXVGpCd0xFWUhxWFFHeEFkdGU=
  KEYCLOAK_IMPORT_CLIENT_SECRET_FHIR_TOOLING: U2VHeEJRNVZNAEh1OUp2RXFkWXQ3S2pMQ2FmY255a3hwV0RzclZ6UDJtWFR3OEZoUmcz
  KEYCLOAK_IMPORT_CLIENT_SECRET_INTEROPERABILITY_LAYER_SPHERES: OHhHRlUySnY2a1haNENzTldnUVZQSHFLelNFVG1iZXlZTG... (base64-encoded)