apiVersion: v1
kind: Secret
metadata:
  name: keycloak-db-credentials
  namespace: keycloak
type: Opaque
data:
  POSTGRES_USER: a2V5Y2xvYWs=
  POSTGRES_PASSWORD: YXVEa0Fid2ZXc3AzSnplNjROeHZCSDJoU0NtcVJHNTg3RXRMVmdkbmpyY01UeTlRVVA=